version: '3'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DATA_DIR=./data
    volumes:
      - "./data:/tmp/localstack/data"
    command: sh -c |
      "aws --endpoint-url=http://localstack:4566 sns create-topic --name myTopic && aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name myQueue"